version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: authservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge